name: Publish Native iOS Library

on: 
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods
        run: sh ./scripts/native-podspec.sh publish
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
