name: Publish NPM Nightly

on:
 schedule:
   - cron: '0 15 * * 1-5'

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm-nightly:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
          cache-dependency-path: '**/package.json'
      - run: |
          npm install
      - name: Version & Publish
        env:
          GH_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npm whoami
          npm run ci:publish:nightly
