name: Publish Native iOS Library

on:
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_15.0.1.app
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods
        run: sh ./scripts/native-podspec.sh publish
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
