name: Publish Native iOS Library

on:
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_16.app
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: '7.x'
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods
        run: sh ./scripts/native-podspec.sh publish
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
