name: Publish NPM Beta

on: workflow_dispatch

jobs:
  deploy-npm-beta:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore Dependency Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          npm whoami
          npm install
      - name: Version & Publish
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npm run ci:publish:beta
